name: Run Finance Analyzer

on:
  schedule:
    - cron: "0 12 * * 1-5"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Run Analyzer
      run: dotnet run --project FinanceAnalyzer/FinanceAnalyzer.csproj

    - name: Upload CSV
      uses: actions/upload-artifact@v3
      with:
        name: Top20Quedas
        path: FinanceAnalyzer/Top20Quedas.csv
